services:

  db:

    image: postgres:16


    environment:
      POSTGRES_DB: ${DB_NAME}           # nome do banco de dados
      POSTGRES_USER: ${DB_USER}         # usuário do banco
      POSTGRES_PASSWORD: ${DB_PASSWORD} # senha do usuário


    volumes:
      - postgres_data:/var/lib/postgresql/data


    healthcheck:
      # pg_isready é um utilitário do próprio Postgres que testa se ele está aceitando conexões.
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s  # testa a cada 5 segundos
      timeout: 5s   # aguarda até 5 segundos por resposta
      retries: 5    # tenta 5 vezes antes de considerar falha


  web:
    
    build: ./backend

    volumes:
      - ./backend:/app


    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
