# Generated by Django 6.0.4 on 2026-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('instrutor', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
